// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/cni.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id is the unique identifier for the container.
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// netns is the path to the network namespace (e.g., /proc/<pid>/ns/net).
	Netns string `protobuf:"bytes,2,opt,name=netns,proto3" json:"netns,omitempty"`
	// if_name is the name of the interface to create in the pod (e.g., "ts0").
	IfName string `protobuf:"bytes,3,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`
	// pod_name is the name of the pod from CNI_ARGS.
	PodName string `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// pod_namespace is the Kubernetes namespace of the pod.
	PodNamespace string `protobuf:"bytes,5,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	// pod_uid is the unique identifier of the pod.
	PodUid string `protobuf:"bytes,6,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	// cluster_ip is the pod's cluster IP (from previous CNI, e.g., flannel).
	ClusterIp string `protobuf:"bytes,7,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`
	// pod_annotations is a map of pod annotations (key-value pairs).
	PodAnnotations map[string]string `protobuf:"bytes,8,rep,name=pod_annotations,json=podAnnotations,proto3" json:"pod_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_pkg_proto_cni_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cni_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cni_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *AddRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *AddRequest) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *AddRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AddRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *AddRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *AddRequest) GetClusterIp() string {
	if x != nil {
		return x.ClusterIp
	}
	return ""
}

func (x *AddRequest) GetPodAnnotations() map[string]string {
	if x != nil {
		return x.PodAnnotations
	}
	return nil
}

type AddResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tailscale_ipv4 is the assigned Tailscale IPv4 address (e.g., "100.64.1.10").
	TailscaleIpv4 string `protobuf:"bytes,1,opt,name=tailscale_ipv4,json=tailscaleIpv4,proto3" json:"tailscale_ipv4,omitempty"`
	// tailscale_ipv6 is the assigned Tailscale IPv6 address if available.
	TailscaleIpv6 string `protobuf:"bytes,2,opt,name=tailscale_ipv6,json=tailscaleIpv6,proto3" json:"tailscale_ipv6,omitempty"`
	// tailscale_hostname is the hostname registered in the tailnet.
	TailscaleHostname string `protobuf:"bytes,3,opt,name=tailscale_hostname,json=tailscaleHostname,proto3" json:"tailscale_hostname,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_pkg_proto_cni_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cni_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cni_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetTailscaleIpv4() string {
	if x != nil {
		return x.TailscaleIpv4
	}
	return ""
}

func (x *AddResponse) GetTailscaleIpv6() string {
	if x != nil {
		return x.TailscaleIpv6
	}
	return ""
}

func (x *AddResponse) GetTailscaleHostname() string {
	if x != nil {
		return x.TailscaleHostname
	}
	return ""
}

type DelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id is the unique identifier for the container.
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// netns is the path to the network namespace.
	Netns string `protobuf:"bytes,2,opt,name=netns,proto3" json:"netns,omitempty"`
	// if_name is the name of the interface to remove.
	IfName        string `protobuf:"bytes,3,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_pkg_proto_cni_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cni_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cni_proto_rawDescGZIP(), []int{2}
}

func (x *DelRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DelRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *DelRequest) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

type DelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_pkg_proto_cni_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cni_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cni_proto_rawDescGZIP(), []int{3}
}

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id is the unique identifier for the container.
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// netns is the path to the network namespace.
	Netns string `protobuf:"bytes,2,opt,name=netns,proto3" json:"netns,omitempty"`
	// if_name is the name of the interface to check.
	IfName        string `protobuf:"bytes,3,opt,name=if_name,json=ifName,proto3" json:"if_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_pkg_proto_cni_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cni_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cni_proto_rawDescGZIP(), []int{4}
}

func (x *CheckRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CheckRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *CheckRequest) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy indicates whether the pod's Tailscale connection is healthy.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// message provides additional details about the health status.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_pkg_proto_cni_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_cni_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_cni_proto_rawDescGZIP(), []int{5}
}

func (x *CheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *CheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_cni_proto protoreflect.FileDescriptor

const file_pkg_proto_cni_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/cni.proto\x12\ftailscalecni\"\xf0\x02\n" +
	"\n" +
	"AddRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05netns\x18\x02 \x01(\tR\x05netns\x12\x17\n" +
	"\aif_name\x18\x03 \x01(\tR\x06ifName\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x05 \x01(\tR\fpodNamespace\x12\x17\n" +
	"\apod_uid\x18\x06 \x01(\tR\x06podUid\x12\x1d\n" +
	"\n" +
	"cluster_ip\x18\a \x01(\tR\tclusterIp\x12U\n" +
	"\x0fpod_annotations\x18\b \x03(\v2,.tailscalecni.AddRequest.PodAnnotationsEntryR\x0epodAnnotations\x1aA\n" +
	"\x13PodAnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\vAddResponse\x12%\n" +
	"\x0etailscale_ipv4\x18\x01 \x01(\tR\rtailscaleIpv4\x12%\n" +
	"\x0etailscale_ipv6\x18\x02 \x01(\tR\rtailscaleIpv6\x12-\n" +
	"\x12tailscale_hostname\x18\x03 \x01(\tR\x11tailscaleHostname\"^\n" +
	"\n" +
	"DelRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05netns\x18\x02 \x01(\tR\x05netns\x12\x17\n" +
	"\aif_name\x18\x03 \x01(\tR\x06ifName\"\r\n" +
	"\vDelResponse\"`\n" +
	"\fCheckRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05netns\x18\x02 \x01(\tR\x05netns\x12\x17\n" +
	"\aif_name\x18\x03 \x01(\tR\x06ifName\"C\n" +
	"\rCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc8\x01\n" +
	"\fTailscaleCNI\x12:\n" +
	"\x03Add\x12\x18.tailscalecni.AddRequest\x1a\x19.tailscalecni.AddResponse\x12:\n" +
	"\x03Del\x12\x18.tailscalecni.DelRequest\x1a\x19.tailscalecni.DelResponse\x12@\n" +
	"\x05Check\x12\x1a.tailscalecni.CheckRequest\x1a\x1b.tailscalecni.CheckResponseB,Z*github.com/jakedgy/tailscale-cni/pkg/protob\x06proto3"

var (
	file_pkg_proto_cni_proto_rawDescOnce sync.Once
	file_pkg_proto_cni_proto_rawDescData []byte
)

func file_pkg_proto_cni_proto_rawDescGZIP() []byte {
	file_pkg_proto_cni_proto_rawDescOnce.Do(func() {
		file_pkg_proto_cni_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_cni_proto_rawDesc), len(file_pkg_proto_cni_proto_rawDesc)))
	})
	return file_pkg_proto_cni_proto_rawDescData
}

var file_pkg_proto_cni_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_cni_proto_goTypes = []any{
	(*AddRequest)(nil),    // 0: tailscalecni.AddRequest
	(*AddResponse)(nil),   // 1: tailscalecni.AddResponse
	(*DelRequest)(nil),    // 2: tailscalecni.DelRequest
	(*DelResponse)(nil),   // 3: tailscalecni.DelResponse
	(*CheckRequest)(nil),  // 4: tailscalecni.CheckRequest
	(*CheckResponse)(nil), // 5: tailscalecni.CheckResponse
	nil,                   // 6: tailscalecni.AddRequest.PodAnnotationsEntry
}
var file_pkg_proto_cni_proto_depIdxs = []int32{
	6, // 0: tailscalecni.AddRequest.pod_annotations:type_name -> tailscalecni.AddRequest.PodAnnotationsEntry
	0, // 1: tailscalecni.TailscaleCNI.Add:input_type -> tailscalecni.AddRequest
	2, // 2: tailscalecni.TailscaleCNI.Del:input_type -> tailscalecni.DelRequest
	4, // 3: tailscalecni.TailscaleCNI.Check:input_type -> tailscalecni.CheckRequest
	1, // 4: tailscalecni.TailscaleCNI.Add:output_type -> tailscalecni.AddResponse
	3, // 5: tailscalecni.TailscaleCNI.Del:output_type -> tailscalecni.DelResponse
	5, // 6: tailscalecni.TailscaleCNI.Check:output_type -> tailscalecni.CheckResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_cni_proto_init() }
func file_pkg_proto_cni_proto_init() {
	if File_pkg_proto_cni_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_cni_proto_rawDesc), len(file_pkg_proto_cni_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_cni_proto_goTypes,
		DependencyIndexes: file_pkg_proto_cni_proto_depIdxs,
		MessageInfos:      file_pkg_proto_cni_proto_msgTypes,
	}.Build()
	File_pkg_proto_cni_proto = out.File
	file_pkg_proto_cni_proto_goTypes = nil
	file_pkg_proto_cni_proto_depIdxs = nil
}
