// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pkg/proto/cni.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TailscaleCNI_Add_FullMethodName   = "/tailscalecni.TailscaleCNI/Add"
	TailscaleCNI_Del_FullMethodName   = "/tailscalecni.TailscaleCNI/Del"
	TailscaleCNI_Check_FullMethodName = "/tailscalecni.TailscaleCNI/Check"
)

// TailscaleCNIClient is the client API for TailscaleCNI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TailscaleCNI is the service that the daemon exposes to the CNI shim.
type TailscaleCNIClient interface {
	// Add is called when a new pod is created.
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// Del is called when a pod is deleted.
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
	// Check is called to verify the pod's network is healthy.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type tailscaleCNIClient struct {
	cc grpc.ClientConnInterface
}

func NewTailscaleCNIClient(cc grpc.ClientConnInterface) TailscaleCNIClient {
	return &tailscaleCNIClient{cc}
}

func (c *tailscaleCNIClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, TailscaleCNI_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tailscaleCNIClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, TailscaleCNI_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tailscaleCNIClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, TailscaleCNI_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TailscaleCNIServer is the server API for TailscaleCNI service.
// All implementations must embed UnimplementedTailscaleCNIServer
// for forward compatibility.
//
// TailscaleCNI is the service that the daemon exposes to the CNI shim.
type TailscaleCNIServer interface {
	// Add is called when a new pod is created.
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// Del is called when a pod is deleted.
	Del(context.Context, *DelRequest) (*DelResponse, error)
	// Check is called to verify the pod's network is healthy.
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedTailscaleCNIServer()
}

// UnimplementedTailscaleCNIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTailscaleCNIServer struct{}

func (UnimplementedTailscaleCNIServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedTailscaleCNIServer) Del(context.Context, *DelRequest) (*DelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedTailscaleCNIServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedTailscaleCNIServer) mustEmbedUnimplementedTailscaleCNIServer() {}
func (UnimplementedTailscaleCNIServer) testEmbeddedByValue()                      {}

// UnsafeTailscaleCNIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TailscaleCNIServer will
// result in compilation errors.
type UnsafeTailscaleCNIServer interface {
	mustEmbedUnimplementedTailscaleCNIServer()
}

func RegisterTailscaleCNIServer(s grpc.ServiceRegistrar, srv TailscaleCNIServer) {
	// If the following call panics, it indicates UnimplementedTailscaleCNIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TailscaleCNI_ServiceDesc, srv)
}

func _TailscaleCNI_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TailscaleCNIServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TailscaleCNI_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TailscaleCNIServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TailscaleCNI_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TailscaleCNIServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TailscaleCNI_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TailscaleCNIServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TailscaleCNI_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TailscaleCNIServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TailscaleCNI_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TailscaleCNIServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TailscaleCNI_ServiceDesc is the grpc.ServiceDesc for TailscaleCNI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TailscaleCNI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tailscalecni.TailscaleCNI",
	HandlerType: (*TailscaleCNIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _TailscaleCNI_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _TailscaleCNI_Del_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _TailscaleCNI_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/cni.proto",
}
